### PR TITLE
Fix: typo

### PR DESCRIPTION
**Pull request by zJUNAIDz**

### CODE REVIEW

**Review by zJUNAIDz — COMMENTED** [review]
fix some markdown issues + typos

**Review by zJUNAIDz — COMMENTED** [review]
fix some markdown issues + typos

**Comment by irorochad** [comment]
Lol, approving. Thanks.

But this doesn't make you an OSS contributor, lol

**Comment by zJUNAIDz** [comment]
😭Step 0 to OSS contribution 😅

**Pull request merged**
